import { getTenantContext } from "@/lib/get-tenant-context";
import { BoldProvider } from "@/components/providers/bold-provider";
import {
  getThemeFromSettings,
  getCssOverrides,
  generateThemeCss,
} from "@/lib/theme-css";
import "./globals.css";

export const dynamic = "force-dynamic";

export const metadata = {
  title: "Bold Demo Site",
  description: "Generated by bold.video",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const context = await getTenantContext();
  const settings = context?.settings;

  // Theme configuration (BOLD-925)
  // Note: No header in nolayout routes (embed only), so header_size is not needed
  const theme = getThemeFromSettings(settings);
  const cssOverrides = getCssOverrides(settings);

  return (
    <html lang="en">
      <head>
        {theme && (
          <style
            dangerouslySetInnerHTML={{ __html: generateThemeCss(theme) }}
          />
        )}
        {cssOverrides && (
          <style
            dangerouslySetInnerHTML={{
              __html: cssOverrides,
            }}
          />
        )}
      </head>
      <body className="bg-background text-foreground">
        {context ? (
          <BoldProvider
            token={context.tenantToken}
            baseURL={
              process.env.BACKEND_URL || "https://app.boldvideo.io/api/v1"
            }
          >
            {children}
          </BoldProvider>
        ) : (
          children
        )}
      </body>
    </html>
  );
}
